### ISSUE TITLE
Color Picker Issue

### ISSUE THREAD

**Issue by omerblink** [bopoda/ace#17]
The color picker of you theme is not working. But once I click inside the picker it starts working.

<img width="548" alt="screen shot 2016-09-20 at 4 58 09 pm" src="https://cloud.githubusercontent.com/assets/773535/18669279/ab37ab52-7f53-11e6-882f-6cf138161582.png">

**Comment by bopoda** [comment]
@omerblink thanks!

**Comment by bopoda** [comment]
[form-elements.html](http://ace.jeka.by/form-elements.html)

**Comment by omerblink** [comment]
👍🏻 Thanks :)
